#!/bin/bash

echo Arrêt Kodi en Docker...
sudo killall -9 kodi.bin

# Basé sur...
# https://github.com/matthuisman/docker-kodi-headless

echo Arrêt du conteneur...
docker stop kodi-headless
echo Suppression du conteneur...
docker rm kodi-headless
